# registry.gitlab.com/meltano/meltano:latest is also available in GitLab Registry
ARG MELTANO_IMAGE=meltano/meltano:v3.3.1
FROM $MELTANO_IMAGE

WORKDIR /project


# Install any additional requirements
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Copy over Meltano project directory
COPY . .
RUN meltano install

#ARG TIME
ENV TZ="America/Argentina/Buenos_Aires"

# Don't allow changes to containerized project files
ENV MELTANO_PROJECT_READONLY 1

# Define environment to run
ENV MELTANO_ENVIRONMENT=docker

RUN chmod +x /project/entrypoint.sh

ENTRYPOINT ["sh"]

