version: 1
default_environment: dev
project_id: 5c0bae1f-74a9-4607-929b-bf4b4ce645a5

jobs:
- name: e2e
  tasks:
  - tap-s3-csv-landing  
  - target-s3-csv-bronze
  - tap-s3-csv-bronze  
  - target-duckdb-raw 
  - dbt-duckdb:clean
  - dbt-duckdb:deps
  - dbt-duckdb:build
- name: dbt-duck
  tasks:
  - dbt-duckdb:clean
  - dbt-duckdb:deps
  - dbt-duckdb:build

####### ENVS  #######
environments:
- name: dev
  env:
    S3_ENDPOINT: http://localhost:9090/
- name: docker
  env:
    S3_ENDPOINT: http://minio:9000/ # 9000 is internal Docker network port for minio service
- name: aws
  env:
    S3_ENDPOINT: https://s3.amazonaws.com
  config:
    plugins:
      extractors:
      - name: tap-s3-csv-landing
        config:
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          bucket: ${AWS_SOURCE_BUCKET}
          tables:
          - table_name: flights
            search_prefix: ${AWS_PREFIX}     # Bucket prefix
            search_pattern: ${AWS_SOURCE_PREFIX}     # Starts with  flights_2009*.csv
      - name: tap-s3-csv-bronze
        config:
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          bucket: ${AWS_DESTINATION_BUCKET}
          tables:
          - table_name: flights_raw
            search_prefix: ${AWS_DESTINATION_PREFIX} 
            search_pattern: ${DEST_FILE}
      loaders:
      - name: target-s3-csv-bronze
        config:
          s3_bucket: ${AWS_DESTINATION_BUCKET}
          s3_key_prefix: ${AWS_DESTINATION_PREFIX}    

####### PLUGINS #######
plugins:
  extractors:
  - name: tap-s3-csv
    variant: transferwise
    pip_url: pipelinewise-tap-s3-csv
    config:
      start_date: '2005-01-01T00:00:00Z'
      aws_access_key_id: ${MINIO_ACCESS_KEY_ID}
      aws_secret_access_key: ${MINIO_SECRET_ACCESS_KEY}
      aws_endpoint_url: ${S3_ENDPOINT}
  - name: tap-s3-csv-landing
    inherit_from: tap-s3-csv
    config:
      bucket: ${MINIO_SOURCE_BUCKET}
      tables:
      - table_name: flights
        search_prefix: ${MINIO_SOURCE_PREFIX}
        search_pattern: ${SRC_FILE} # ^flights_2009.csv Starts with in S3
        # key_properties: [Year, Month, DayofMonth, DepTime, UniqueCarrier, FlightNum]
  - name: tap-s3-csv-bronze
    inherit_from: tap-s3-csv
    config:
      bucket: ${MINIO_DESTINATION_BUCKET}
      tables:
      - table_name: flights_raw
        search_prefix: ${MINIO_DESTINATION_PREFIX}
        search_pattern: ${DEST_FILE}

  loaders:
  - name: target-s3-csv
    variant: transferwise
    pip_url: git+https://github.com/transferwise/pipelinewise-target-s3-csv.git
    config:
      aws_access_key_id: ${MINIO_ACCESS_KEY_ID}
      aws_secret_access_key: ${MINIO_SECRET_ACCESS_KEY}
      aws_endpoint_url: ${S3_ENDPOINT}
  - name: target-s3-csv-bronze
    inherit_from: target-s3-csv
    namespace: write_to_bronze
    config:
      s3_bucket: ${MINIO_DESTINATION_BUCKET}
      s3_key_prefix: ${MINIO_DESTINATION_PREFIX}
      naming_convention: ${DEST_FILE}
  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.6
  - name: target-duckdb-raw
    inherit_from: target-duckdb
    config:
      path: $MELTANO_PROJECT_ROOT/${DDB_PATH}
      dbname: ${DBNAME}
      default_target_schema: ${SCHEMA}
      add_metadata_columns: true
      primary_key_required: false
  utilities:
  - name: dbt-duckdb
    variant: jwills
    pip_url: dbt-core dbt-duckdb git+https://github.com/meltano/dbt-ext.git@main
    config:
      path: $MELTANO_PROJECT_ROOT/${DDB_PATH}
      schema: ${SCHEMA}

